[package]
name = "mailx-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }

sqlx = { version = "0.8", default-features = false, features = [
    "runtime-tokio",
    "sqlite",
    "macros",
    "chrono",
    "migrate",
] }
chrono = { version = "0.4", features = ["serde"] }
directories = "5"

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
tempfile = "3"
