[package]
name = "mailx-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
futures = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }

mailx-proto = { workspace = true }
mailx-store = { workspace = true }

keyring = { version = "3", features = [
    "apple-native",
    "windows-native",
    "sync-secret-service",
    "crypto-rust",
] }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "sqlite"] }
